name: Linux tests

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Build a wheel via an sdist
      run: |
        pip install build
        python -m build
        pip install dist/pyxai*.whl
    - name: Run test suite
      run: |
        python -m pyxai --tests